### ISSUE TITLE
Can we customize the skipping rope algorithm

### ISSUE THREAD

**Issue by q4908800** [chenwr727/RopeSkippingCounter#2]
Can we customize the skipping rope algorithm

**Comment by chenwr727** [comment]
Can you provide some examples of customized skipping rope algorithms?

**Comment by q4908800** [comment]
Our program runs on the WeChat mini program end. Can we use TensorFlow's Posenet model to create a version of the skipping rope algorithm that can be run on the web

**Comment by chenwr727** [comment]
Yes, you can refer to the following

- [tfjs-models](https://github.com/tensorflow/tfjs-models)
- [wxmp-tensorflow](https://github.com/deepkolos/wxmp-tensorflow)
